config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :member_course_interests

  map.resources :members, :collection => { :autocomplete_for_member_emailid => :get}

  map.resources :member_general_feedbacks
  
  map.root :controller => "member_attendances", :action => "schedules"
  
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"

  map.memberreport "memberreport", :controller => "member_report"
  
  map.resources :user_sessions
  map.resources :crs_schedules
  map.resources :course_schedules, :has_many => :member_courses
  map.resources :recurring_events
  map.resources :centers
  
  map.resources :users
  map.connect "member_attendances/choosecenter", :controller => "member_attendances", :action => "choosecenter"
  map.connect "member_attendances/submitcenterchoice", :controller => "member_attendances", :action => "submitcenterchoice"
  map.resources :member_attendances, :action => "success"
  
  map.resources :members, :action => "save_tags"
  map.resources :members, :action => "save_notes"
  map.resources :members, :action => "save_fdate"
  map.resources :members, :action => "add_connection"

  map.resources :members, :has_many => :member_general_feedbacks
  map.resources :members, :has_many => :member_courses
  map.resources :members, :has_many => :member_course_interests

  map.resources :member_courses
  map.connections "myconnections", :controller => "members", :action => "index", :myconn => "myconnections"
  
  map.resources :login

  map.resources :courses, :has_many => :course_schedules
  map.resources :courses, :has_many => :recurring_events
  map.resources :tags
  

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/center.rb
class Center < ActiveRecord::Base
  has_many :members
  has_many :tags
  has_many :member_attendances
  has_many :course_schedules
  has_many :recurring_events
  validates_presence_of :city, :state

  def location
    (city ? city.camelcase : "") + ", " + (state ? state.camelcase : "")
    #firstname.nil? firstname.capitalize  + " " + lastname.capitalize unless lastname.nil?
  end

end

app/controllers/member_report_controller.rb
class MemberReportController < ApplicationController
  add_crumb("Member Report") { |instance| instance.send :memberreport_path }

  def index
    @courses = Course.find(:all)
    @courseschedules = CourseSchedule.find(:all, :conditions => ["center_id = ?", session[:center_id]], :order => "start_date desc").paginate :page => params[:page], :per_page => 10
    @cs_id = -1


    respond_to do |format|
      format.html
      format.xml  { render :xml => @members }
    end
  end

  def show
    @courses = Course.find(:all)

    if !params[:from_date_cal].empty?
      @report_start_date = Time.parse(params[:from_date_cal])
    end
    if !params[:end_date_cal].empty?
      @report_end_date = Time.parse(params[:end_date_cal])
    end


    @coursedd = params[:coursedd] unless params[:coursedd][:id].empty?


    #if @report_start_date.nil? or @report_end_date.nil?
    # @courseschedules = CourseSchedule.find(:all, :conditions => ["course_id=?", params[:coursedd][:id]]).paginate :page => params[:page], :per_page => 10
    #else
    #      @courseschedules = CourseSchedule.find(:all, :conditions => ["start_date >= ? and end_date <= ? and course_id=?", @report_start_date, @report_end_date, params[:coursedd][:id]]).paginate :page => params[:page], :per_page => 10
    #   end
    @courseschedules ||= find_course_schedules.paginate :page => params[:page], :per_page => 10
    @cs_id = -1

    respond_to do |format|
      format.html
      format.xml  { render :xml => @members }
    end
  end

  def build_date_from_params(field_name, params)
    if params["#{field_name.to_s}(1i)"].empty?
      return
    else
      puts "no"
      Date.new(params["#{field_name.to_s}(1i)"].to_i,
        params["#{field_name.to_s}(2i)"].to_i,
        params["#{field_name.to_s}(3i)"].to_i)
    end
  end

  def composemessage
    puts params[:course_schedule_radio]
    @cs_id = params[:course_schedule_radio]

    @cs = CourseSchedule.find(@cs_id)
    @member_attendances = @cs.member_attendances
    @email_ids = []
    @member_attendances.each_with_index do |att, i|
      unless att.member.nil?
        @eid = att.member.emailid
        unless @email_ids.include?(@eid + ",")
          if i == @member_attendances.size - 1
            @email_ids << @eid
          else
            @email_ids << @eid + ","
          end
        end
      end
    end

    respond_to do |format|
      format.html
    end

  end

  def confirmmembers
    @cs_id = params[:cs_id]
    @member_courses = MemberCourse.find(:all, :conditions => ["course_schedule_id=?", @cs_id])
    @email_ids = []
    @member_courses.each do |member_course|
      @email_ids << member_course.member.emailid
    end

    puts @email_ids
    puts @cs_id
    respond_to do |format|
      format.html
    end
  end

  def sendemail
    @cs_id = params[:cs_id]
    @member_courses = MemberCourse.find(:all, :conditions => ["course_schedule_id=?", @cs_id])
    @email_ids = []
    @member_courses.each do |member_course|
      if !@email_ids.include?(member_course.member.emailid)
        # MemberMailer.deliver_sendemail_for_members("santaclara@us.artofliving.org", member_course.member.emailid, params[:subject], nil, params[:email_content].gsub('{FIRSTNAME}', member_course.member.firstname))
        @email_ids << member_course.member.emailid
      end
    end

    # flash[:notice] = "Email(s) sent !"
    flash[:notice] = "Email feature is currently disabled."
    redirect_to :action => "index"
  end

  def update_course_schedules
    @courses = Course.find(params[:coursedd][:id])
    @cls = @courses.course_schedules

    render :update do |page|
      page.replace_html 'courseschedules', :partial => 'courseschedules', :object => @cls
    end
  end

  private
  def find_course_schedules
    CourseSchedule.find(:all, :conditions => conditions, :order => "start_date desc")
  end

  def id_conditions
    ["course_id = ?", params[:coursedd][:id]] unless params[:coursedd][:id].empty?
  end

 def center_conditions
    ["center_id = ?", session[:center_id]]
 end

  def start_date_conditions
    if !params[:from_date_cal].empty?
      @report_start_date = Date.parse(params[:from_date_cal])
      ["start_date >= ?", @report_start_date]
    end
  end

  def end_date_conditions
    if !params[:end_date_cal].empty?
      @report_end_date = Date.parse(params[:end_date_cal])
      ["start_date <= ?", @report_end_date]
    end
  end

  def conditions
    [conditions_clauses.join(' AND '), *conditions_options]
  end

  def conditions_clauses
    conditions_parts.map { |condition| condition.first }
  end

  def conditions_options
    conditions_parts.map { |condition| condition[1..-1] }.flatten
  end

  def conditions_parts
    private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
  end
end

app/views/member_report/_courseschedules.html.erb
<%= collection_select(nil, :id, @cls, :id, :start_date, {:prompt => "Select a courseSchedule"}) %>

app/views/member_report/completionstatus.html.erb
<b>Email sent !</b>

app/views/member_report/composemessage.html.erb
<% form_tag '/member_report/sendemail' do -%>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
<tr><td colspan="3">&nbsp;<font color="red">Send email not enabled yet. Please checkout later !</font></td></tr>
<tr><td><br><b>Subject</b>&nbsp;</td><td valign="bottom"><%= text_field_tag "subject", "", :size => 70 %></td><td>&nbsp;</td></tr>
<tr><td colspan="3">&nbsp;</td></tr>
<tr><td><br><b>To</b>&nbsp;</td><td valign="top"><%= text_area_tag "to", @email_ids, :size => "80x6" %></td><td>&nbsp;</td></tr>
<!--<tr><td colspan="2"><br><b>Choose option to where to put Member Email Ids</b><br>
&nbsp;&nbsp;&nbsp;To&nbsp;<%= radio_button_tag "emailid_option","To" %>
&nbsp;&nbsp;&nbsp;Bcc&nbsp;<%= radio_button_tag "emailid_option","Bcc" %>
&nbsp;&nbsp;&nbsp;Cc&nbsp;<%= radio_button_tag "emailid_option","Cc" %>
</td>
</tr>-->
<tr><td colspan="3">&nbsp;</td></tr>
<tr><td>&nbsp;</td><td colspan="2">Variables:</td></tr>
<tr><td>&nbsp;</td><td colspan="2">First name - {FIRSTNAME}</td></tr>
<tr><td valign="top"><b>Content</b>&nbsp;</td><td valign="bottom"><%= text_area_tag 'email_content', nil, :size => "75x40" %></td><td>&nbsp;</td></tr>
</table>
<br>

<%=  hidden_field_tag 'cs_id', @cs_id %>
<% end -%>

app/views/member_report/confirmmembers.erb
<br><br>
<table border="0" cellspacing="0" cellpadding="0" width="80%">
  <tr>
    <td>
      <% form_tag '/member_reports/completionstatus' do -%>
      An email will be sent to the following members. Click Confirm to send emails or click Back to discontinue.<br><br>
      <%=  @email_ids %>
      <br><br>
      <%=  hidden_field_tag 'cs_id', @cs_id %>
      <%= submit_tag "Send Email" %>
      <%= button_to "Back", '/member_reports/composemessage' %>
      <% end -%>
    </td>
  </tr>
</table>

app/views/member_report/index.html.erb
<%= javascript_include_tag :defaults %>
<%= calendar_date_select_includes "silver" %>
<br><br>
<table border="0" cellspacing="0" cellpadding="0" width="80%">
  <tr>
    <td>
      <table border="0" cellspacing="0" cellpadding="0" width="100%">
        <tr><td><b>Search courses/events</b></td></tr>
        <tr>
          <td>
            <% form_tag '/member_report/show', :method => 'get' do -%>
    <label for ="coursename">Course</label>&nbsp;&nbsp;
      <%= collection_select(:coursedd, :id, @courses, :id, :displayName,
                            {:prompt => "Select a Course"})%>&nbsp;&nbsp;<label for ="startdate">From Date</label>&nbsp;&nbsp;<%= calendar_date_select_tag "from_date_cal", @sel_from_date, :year_range => 3.years.ago..0.years.ago%>&nbsp;&nbsp;<label for ="enddate"> To Date </label>&nbsp;&nbsp;<%= calendar_date_select_tag "end_date_cal", @sel_end_date, :year_range => 3.years.ago..0.years.ago%>&nbsp;&nbsp;<%= submit_tag 'Search',:action => "show" %>
            <% end -%>
          </td>
        </tr>
        <tr><td>&nbsp;</td></tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <% form_tag '/member_report/composemessage' do -%>
      <table border="1" cellspacing="0" cellpadding="5" width="100%">
  <tr bgcolor="#A9F5F2">
    <td width="40"><b> Select </b></td>
    <td width="100"><b>Course</b></td>
    <td width="100"><b>Course Start Date</b></td>
    <td width="100"><b>Attended</b></td>
    <td width="100"><b>Teacher</b></td>

  <% for courseschedule in @courseschedules -%>
  <tr>
    <td><%= radio_button_tag  "course_schedule_radio", courseschedule.id %></td>
    <td><%= courseschedule.course.displayName %> </td>
    <td><%= courseschedule.start_date.strftime("%m-%d-%Y") %></td>
     <td><%= link_to courseschedule.member_attendances.count(), {:controller=>"members", :action=>"index", :csid=>courseschedule.id} %> </td>
    <td><%= courseschedule.teacher.fullname unless courseschedule.teacher.nil? %> </td>
  </tr>
<% end %>
      </table>
      <%= submit_tag "Get Email IDs" %>
      <% end -%>
</td>
  </tr>
   <tr>
   <td align="right"><br>
    <%= will_paginate @courseschedules %>
   </td>
 </tr>

</table>

app/views/member_report/members_list.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

  <tr>
    <td>
      <% form_tag '/member_report/composemessage' do -%>
      <table border="1" cellspacing="0" cellpadding="5" width="100%">
  <tr bgcolor="#A9F5F2">
    <td width="40"><b> Select </b></td>
    <td width="100"><b>Name</b></td>
    <td width="100"><b>Email</b></td>
    <td width="130"><b>Phone</b></td>
  </tr>

<% for member in @members -%>
  <tr>
    <td><%= check_box_tag  "member_ids[]", member.id %></td>
    <td><%= member.firstname %>&nbsp;<%= member.lastname %></td>
    <td><%=h member.emailid %></td>
    <td><%=h member.homephone %></td>
  </tr>
<% end %>
      </table>
      <%= submit_tag "Compose Message" %>
      <% end -%>
</td>
  </tr>

app/views/member_report/show.html.erb
<%= javascript_include_tag :defaults %>
<%= calendar_date_select_includes "silver" %>
<br><br>
<table border="0" cellspacing="0" cellpadding="0" width="80%">
  <tr>
    <td>
      <table border="0" cellspacing="0" cellpadding="0" width="100%">
        <tr><td><b>Search courses/events</b></td></tr>
        <tr>
          <td>
            <% form_tag '/member_report/show', :method => 'get' do -%>
    <label for ="coursename">Course</label>&nbsp;&nbsp;
      <%= collection_select(:coursedd, :id, @courses, :id, :displayName,
                            {:prompt => "Select a Course"})%>&nbsp;&nbsp;<label for ="startdate">From Date</label>&nbsp;&nbsp;<%= calendar_date_select_tag "from_date_cal", @sel_from_date, :year_range => 3.years.ago..0.years.ago%>&nbsp;&nbsp;<label for ="enddate"> To Date </label>&nbsp;&nbsp;<%= calendar_date_select_tag "end_date_cal", @sel_end_date, :year_range => 3.years.ago..0.years.ago%>&nbsp;&nbsp;<%= submit_tag 'Search',:action => "show" %>
            <% end -%>
          </td>
        </tr>
        <tr><td>&nbsp;</td></tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <% form_tag '/member_report/composemessage' do -%>
      <table border="1" cellspacing="0" cellpadding="5" width="100%">
  <tr bgcolor="#A9F5F2">
    <td width="40"><b> Select </b></td>
    <td width="100"><b>Course</b></td>
    <td width="100"><b>Course Start Date</b></td>
    <td width="100"><b>Attended</b></td>
    <td width="100"><b>Teacher</b></td>

  <% for courseschedule in @courseschedules -%>
  <tr>
    <td><%= radio_button_tag  "course_schedule_radio", courseschedule.id %></td>
    <td><%= courseschedule.course.displayName %> </td>
    <td><%= courseschedule.start_date.strftime("%m-%d-%Y") %></td>
     <td><%= link_to courseschedule.member_attendances.count(), {:controller=>"members", :action=>"index", :csid=>courseschedule.id} %> </td>
    <td><%= courseschedule.teacher.fullname unless courseschedule.teacher.nil? %> </td>
  </tr>
<% end %>
      </table>
      <%= submit_tag "Get Email IDs" %>
      <% end -%>
</td>
  </tr>
   <tr>
   <td align="right"><br>
    <%= will_paginate @courseschedules %>
   </td>
 </tr>

</table>